// src/schema.ts
// Phase A: a DomainSchema is a small finite Category (Objects + generating
// Morphisms, free on that graph — no path equations yet, that's Phase B's
// SchemaMapping territory). An Instance is a finite Set-valued functor
// I : C → Set, given concretely as row sets per Object and a total
// function per Morphism.
//
// checkInstanceIsFunctor() verifies the functor laws for the free
// category generated by the schema graph. For a free category, functor
// laws reduce to exactly two conditions per generating morphism:
//   (1) totality      — the function is defined on every row of its source
//   (2) codomain valid — every value it returns actually exists in its target
// Composite morphisms are automatically functorial in Set once every
// generator is (function composition in Set is associative "for free"),
// so nothing further needs checking here as long as no equations are
// declared between paths.
//
// This is deliberately the same condition engineers already call
// "referential integrity" — the point is that referential integrity
// *is* functoriality, not an analogy for it.

export type AttributeType = 'string' | 'number' | 'boolean' | 'date';

export interface AttributeDef {
  name: string;
  type: AttributeType;
}

/** An Object of the schema category: a labeled record shape. */
export interface ObjectDef {
  attributes: AttributeDef[];
}

/** A generating Morphism of the schema category: a total function A → B. */
export interface MorphismDef {
  name: string;
  from: string; // source object name
  to: string;   // target object name
}

/** DomainSchema = a finite Category, given as a graph that generates it freely. */
export interface DomainSchema {
  objects: Record<string, ObjectDef>;
  morphisms: MorphismDef[];
}

/** A row is an element of an Object's underlying set, identified by id. */
export interface Row {
  id: string;
  [attribute: string]: unknown;
}

/**
 * Instance = a finite functor I : C → Set.
 *   rows[objectName]            = I(objectName), the underlying set
 *   fk[morphismName][sourceId]  = I(morphism) applied to that element
 */
export interface Instance {
  rows: Record<string, Row[]>;
  fk: Record<string, Record<string, string>>;
}

export type FunctorViolationReason =
  | 'unknown-source-object'
  | 'unknown-target-object'
  | 'not-total'
  | 'dangling-reference';

export interface FunctorViolation {
  morphism: string;
  sourceObject: string;
  targetObject: string;
  rowId: string;
  reason: FunctorViolationReason;
  detail: string;
}

export interface FunctorCheckReport {
  isFunctor: boolean;
  violations: FunctorViolation[];
  checkedMorphisms: number;
  checkedRows: number;
}

/**
 * Verifies that `instance` is a valid Set-valued functor on the free
 * category generated by `schema`. Every violation found corresponds to
 * something engineers would independently call a data quality bug —
 * that correspondence is the point, not a coincidence.
 */
export function checkInstanceIsFunctor(
  schema: DomainSchema,
  instance: Instance,
): FunctorCheckReport {
  const violations: FunctorViolation[] = [];
  let checkedRows = 0;

  for (const m of schema.morphisms) {
    const sourceRows = instance.rows[m.from];
    const targetRows = instance.rows[m.to];

    if (!sourceRows) {
      violations.push({
        morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: '',
        reason: 'unknown-source-object',
        detail: `instance has no rows for object "${m.from}" (required as the source of morphism "${m.name}")`,
      });
      continue;
    }
    if (!targetRows) {
      violations.push({
        morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: '',
        reason: 'unknown-target-object',
        detail: `instance has no rows for object "${m.to}" (required as the target of morphism "${m.name}")`,
      });
      continue;
    }

    const targetIds = new Set(targetRows.map((r) => r.id));
    const fkMap = instance.fk[m.name] ?? {};

    for (const row of sourceRows) {
      checkedRows++;
      const mapped = fkMap[row.id];

      if (mapped === undefined) {
        violations.push({
          morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: row.id,
          reason: 'not-total',
          detail: `row "${row.id}" of "${m.from}" has no value under morphism "${m.name}" — a functor must be defined on every element of its source`,
        });
        continue;
      }
      if (!targetIds.has(mapped)) {
        violations.push({
          morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: row.id,
          reason: 'dangling-reference',
          detail: `row "${row.id}" of "${m.from}" maps via "${m.name}" to "${mapped}", which does not exist in "${m.to}" — orphaned foreign key`,
        });
      }
    }
  }

  return {
    isFunctor: violations.length === 0,
    violations,
    checkedMorphisms: schema.morphisms.length,
    checkedRows,
  };
}

/** Ergonomic builder — raw object-literal Instances are clunky to write by hand. */
export class InstanceBuilder {
  private rowsByObject: Record<string, Row[]> = {};
  private fkByMorphism: Record<string, Record<string, string>> = {};

  addRow(object: string, row: Row): this {
    (this.rowsByObject[object] ??= []).push(row);
    return this;
  }

  addRows(object: string, rows: Row[]): this {
    for (const r of rows) this.addRow(object, r);
    return this;
  }

  setFk(morphism: string, sourceRowId: string, targetRowId: string): this {
    (this.fkByMorphism[morphism] ??= {})[sourceRowId] = targetRowId;
    return this;
  }

  build(): Instance {
    return { rows: this.rowsByObject, fk: this.fkByMorphism };
  }
}

/**
 * Derives the lightweight human-readable / prompt-facing schema shape
 * (`DomainDefinition.schema` / `.relations`) from a typed DomainSchema,
 * so a domain author only has to write the structured version once.
 */
export function describeSchema(schema: DomainSchema): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [objName, def] of Object.entries(schema.objects)) {
    out[objName] = def.attributes.map((a) => `${a.name}: ${a.type}`).join(', ');
  }
  return out;
}

export function describeMorphisms(
  schema: DomainSchema,
): { from: string; to: string; label?: string }[] {
  return schema.morphisms.map((m) => ({ from: m.from, to: m.to, label: m.name }));
}
