// src/schema.ts
// Phase A: a DomainSchema is a small finite Category (Objects + generating
// Morphisms, free on that graph — no path equations yet, that's Phase B's
// SchemaMapping territory). An Instance is a finite Set-valued functor
// I : C → Set, given concretely as row sets per Object and a total
// function per Morphism.
//
// checkInstanceIsFunctor() verifies the functor laws for the free
// category generated by the schema graph. For a free category, functor
// laws reduce to exactly two conditions per generating morphism:
//   (1) totality      — the function is defined on every row of its source
//   (2) codomain valid — every value it returns actually exists in its target
// Composite morphisms are automatically functorial in Set once every
// generator is (function composition in Set is associative "for free"),
// so nothing further needs checking here as long as no equations are
// declared between paths.
//
// This is deliberately the same condition engineers already call
// "referential integrity" — the point is that referential integrity
// *is* functoriality, not an analogy for it.

export type AttributeType = 'string' | 'number' | 'boolean' | 'date';

export interface AttributeDef {
  name: string;
  type: AttributeType;
}

/** An Object of the schema category: a labeled record shape. */
export interface ObjectDef {
  attributes: AttributeDef[];
}

/** A generating Morphism of the schema category: a total function A → B. */
export interface MorphismDef {
  name: string;
  from: string; // source object name
  to: string;   // target object name
}

/** DomainSchema = a finite Category, given as a graph that generates it freely,
 * plus (optionally) declared path equations for the non-free case. */
export interface DomainSchema {
  objects: Record<string, ObjectDef>;
  morphisms: MorphismDef[];
  /**
   * Declared path equations (Phase D). SCOPE: two paths are only
   * considered equal if they are syntactically identical OR appear as
   * an explicitly declared equation here — this is NOT a congruence
   * closure (it will not automatically derive that f;p = f;q from
   * p = q). That closure computation is the genuinely hard, word-
   * problem-adjacent part of Functorial Data Migration and is out of
   * scope. What IS in scope, and fully decidable: (a) checking whether
   * a concrete finite Instance satisfies its schema's declared
   * equations (checkInstanceIsFunctor, below), and (b) checking whether
   * a SchemaMapping sends declared-equal paths to declared-equal paths
   * (checkSchemaMappingLaws, in ./schemaMapping). Both are finite,
   * always-terminating computations — the undecidability of the general
   * word problem never enters into them.
   */
  equations?: PathEquation[];
}

/** A declared path equation: `left` and `right`, both starting at object `from`, must land on the same row for every element of `from`. */
export interface PathEquation {
  /** human-readable name, e.g. "memberOf;partOf = directDept" */
  name: string;
  /** the shared object both paths start from */
  from: string;
  left: string[];
  right: string[];
}

/** A row is an element of an Object's underlying set, identified by id. */
export interface Row {
  id: string;
  [attribute: string]: unknown;
}

/**
 * Instance = a finite functor I : C → Set.
 *   rows[objectName]            = I(objectName), the underlying set
 *   fk[morphismName][sourceId]  = I(morphism) applied to that element
 */
export interface Instance {
  rows: Record<string, Row[]>;
  fk: Record<string, Record<string, string>>;
}

export type FunctorViolationReason =
  | 'unknown-source-object'
  | 'unknown-target-object'
  | 'not-total'
  | 'dangling-reference'
  | 'equation-violated';

export interface FunctorViolation {
  morphism: string;
  sourceObject: string;
  targetObject: string;
  rowId: string;
  reason: FunctorViolationReason;
  detail: string;
}

export interface FunctorCheckReport {
  isFunctor: boolean;
  violations: FunctorViolation[];
  checkedMorphisms: number;
  checkedRows: number;
}

export type PathEndpointsResult = { from: string; to: string } | 'unknown-morphism' | 'disconnected';

/**
 * Resolves a path's overall (from, to) endpoints within `schema` by
 * walking its generating morphisms. Shared by checkInstanceIsFunctor
 * (equation checking) and checkSchemaMappingLaws (./schemaMapping) so
 * both use one, tested, implementation of "what does this path connect."
 */
export function resolvePathEndpoints(schema: DomainSchema, path: string[]): PathEndpointsResult {
  const byName = new Map(schema.morphisms.map((m) => [m.name, m]));
  let from: string | undefined;
  let cursor: string | undefined;
  for (const name of path) {
    const m = byName.get(name);
    if (!m) return 'unknown-morphism';
    if (from === undefined) {
      from = m.from;
      cursor = m.from;
    }
    if (cursor !== m.from) return 'disconnected';
    cursor = m.to;
  }
  // empty path: caller must know the anchor object from context (identity)
  return from === undefined ? 'disconnected' : { from, to: cursor as string };
}

function arraysEqual(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((x, i) => x === b[i]);
}

/**
 * Are `pathA` and `pathB` (both starting at object `from`) equal
 * according to `schema`? Equal means: syntactically identical, OR an
 * explicitly declared equation (in either orientation). This is
 * intentionally NOT a congruence closure — see DomainSchema.equations
 * for why that's out of scope, and what remains fully decidable here.
 */
export function pathsAreDeclaredEqual(schema: DomainSchema, from: string, pathA: string[], pathB: string[]): boolean {
  if (arraysEqual(pathA, pathB)) return true;
  return (schema.equations ?? []).some(
    (eq) =>
      eq.from === from &&
      ((arraysEqual(eq.left, pathA) && arraysEqual(eq.right, pathB)) ||
        (arraysEqual(eq.left, pathB) && arraysEqual(eq.right, pathA))),
  );
}

function walkPath(instance: Instance, path: string[], startRowId: string): string | undefined {
  let cursor: string | undefined = startRowId;
  for (const morphName of path) {
    cursor = cursor === undefined ? undefined : instance.fk[morphName]?.[cursor];
    if (cursor === undefined) return undefined;
  }
  return cursor;
}

/**
 * Verifies that `instance` is a valid Set-valued functor on the free
 * category generated by `schema`. Every violation found corresponds to
 * something engineers would independently call a data quality bug —
 * that correspondence is the point, not a coincidence.
 */
export function checkInstanceIsFunctor(
  schema: DomainSchema,
  instance: Instance,
): FunctorCheckReport {
  const violations: FunctorViolation[] = [];
  let checkedRows = 0;

  for (const m of schema.morphisms) {
    const sourceRows = instance.rows[m.from];
    const targetRows = instance.rows[m.to];

    if (!sourceRows) {
      violations.push({
        morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: '',
        reason: 'unknown-source-object',
        detail: `instance has no rows for object "${m.from}" (required as the source of morphism "${m.name}")`,
      });
      continue;
    }
    if (!targetRows) {
      violations.push({
        morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: '',
        reason: 'unknown-target-object',
        detail: `instance has no rows for object "${m.to}" (required as the target of morphism "${m.name}")`,
      });
      continue;
    }

    const targetIds = new Set(targetRows.map((r) => r.id));
    const fkMap = instance.fk[m.name] ?? {};

    for (const row of sourceRows) {
      checkedRows++;
      const mapped = fkMap[row.id];

      if (mapped === undefined) {
        violations.push({
          morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: row.id,
          reason: 'not-total',
          detail: `row "${row.id}" of "${m.from}" has no value under morphism "${m.name}" — a functor must be defined on every element of its source`,
        });
        continue;
      }
      if (!targetIds.has(mapped)) {
        violations.push({
          morphism: m.name, sourceObject: m.from, targetObject: m.to, rowId: row.id,
          reason: 'dangling-reference',
          detail: `row "${row.id}" of "${m.from}" maps via "${m.name}" to "${mapped}", which does not exist in "${m.to}" — orphaned foreign key`,
        });
      }
    }
  }

  for (const eq of schema.equations ?? []) {
    const rows = instance.rows[eq.from] ?? [];
    for (const row of rows) {
      const leftResult = walkPath(instance, eq.left, row.id);
      const rightResult = walkPath(instance, eq.right, row.id);
      // if either side is non-total, that's already reported by the
      // per-morphism checks above — don't double-report here.
      if (leftResult === undefined || rightResult === undefined) continue;
      if (leftResult !== rightResult) {
        violations.push({
          morphism: eq.name,
          sourceObject: eq.from,
          targetObject: '(equation)',
          rowId: row.id,
          reason: 'equation-violated',
          detail: `row "${row.id}" of "${eq.from}": path [${eq.left.join(', ')}] leads to "${leftResult}" but path [${eq.right.join(', ')}] leads to "${rightResult}" — these must agree per equation "${eq.name}"`,
        });
      }
    }
  }

  return {
    isFunctor: violations.length === 0,
    violations,
    checkedMorphisms: schema.morphisms.length,
    checkedRows,
  };
}

/** Ergonomic builder — raw object-literal Instances are clunky to write by hand. */
export class InstanceBuilder {
  private rowsByObject: Record<string, Row[]> = {};
  private fkByMorphism: Record<string, Record<string, string>> = {};

  addRow(object: string, row: Row): this {
    (this.rowsByObject[object] ??= []).push(row);
    return this;
  }

  addRows(object: string, rows: Row[]): this {
    for (const r of rows) this.addRow(object, r);
    return this;
  }

  setFk(morphism: string, sourceRowId: string, targetRowId: string): this {
    (this.fkByMorphism[morphism] ??= {})[sourceRowId] = targetRowId;
    return this;
  }

  build(): Instance {
    return { rows: this.rowsByObject, fk: this.fkByMorphism };
  }
}

/**
 * Derives the lightweight human-readable / prompt-facing schema shape
 * (`DomainDefinition.schema` / `.relations`) from a typed DomainSchema,
 * so a domain author only has to write the structured version once.
 */
export function describeSchema(schema: DomainSchema): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [objName, def] of Object.entries(schema.objects)) {
    out[objName] = def.attributes.map((a) => `${a.name}: ${a.type}`).join(', ');
  }
  return out;
}

export function describeMorphisms(
  schema: DomainSchema,
): { from: string; to: string; label?: string }[] {
  return schema.morphisms.map((m) => ({ from: m.from, to: m.to, label: m.name }));
}
